---
version: '3.6'
services:
  rails: &rails_base
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    command: ["rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    volumes:
      - .:/srv/www/current
      - bundle:/usr/local/bundle
      - node_modules:/usr/local/node_modules
    ports:
      - 3000:3000
    environment:
      - DB_HOST=postgres
    depends_on:
      - redis
      - postgres
    tty: true
    stdin_open: true

  webpacker:
    <<: *rails_base
    command: ["bin/webpack-dev-server"]
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - 3035:3035
    depends_on:
      - rails

  redis:
    image: redis

  postgres:
    image: postgres:10.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ''
      PGDATA: /var/lib/postgresql/data/db-files/
    ports:
      - 5432:5432

volumes:
  bundle:
    driver: local
  db:
    driver: local
  node_modules:
    driver: local
