---
version: '3.6'
services:
  rails: &rails_base
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    command: ["rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    volumes:
      - .:/srv/www/current
      - bundle:/usr/local/bundle
      - node_modules:/usr/local/node_modules
    ports:
      - 3000:3000
    environment:
      - LOCAL_DOCKER=true
      - DB_HOST=mysql
    depends_on:
      - redis
      - mysql
    tty: true
    stdin_open: true

  webpacker:
    <<: *rails_base
    command: ["bin/webpack-dev-server"]
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - 3035:3035
    depends_on:
      - rails

  redis:
    image: redis

  mysql:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: rails
      MYSQL_PASSWORD: rails1234
      MYSQL_ROOT_PASSWORD: rails1234
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password

volumes:
  bundle:
    driver: local
  db:
    driver: local
  node_modules:
    driver: local
